"""
Leetcode 264. Ugly Number II

An ugly number is a positive integer whose prime factors are limited to 2, 3, and 5.

Given an integer n, return the nth ugly number.

Example 1:
    Input: n = 10
    Output: 12
    Explanation: [1, 2, 3, 4, 5, 6, 8, 9, 10, 12] is the sequence of the first 10 ugly numbers.

Example 2:
    Input: n = 1
    Output: 1
    Explanation: 1 has no prime factors, therefore all of its prime factors are limited to 2, 3, and 5.

Constraints:
    1 <= n <= 1690
"""

# ---------------------------
# BRUTE FORCE
# ---------------------------
# Approach:
#   1. Start from 1, for each integer, check if it has only 2, 3, and 5 as prime factors.
#   2. Count ugly numbers until reaching the nth.
# Intuition:
#   Division test for every number and every factor.
# Time Complexity: O(n * logA), where A is the value of the nth ugly number (too slow)
# Space Complexity: O(1)
def is_ugly(num):
    if num == 0: return False
    for p in [2, 3, 5]:
        while num % p == 0:
            num //= p
    return num == 1

def nthUglyNumber_bruteforce(n):
    count, num = 0, 0
    while count < n:
        num += 1
        if is_ugly(num):
            count += 1
    return num

# ---------------------------
# BETTER (Heap/Set)
# ---------------------------
# Approach:
#   Simulate the generation of ugly numbers using a min-heap and set to deduplicate.
#   For each pop, multiply by 2,3,5 and add unseen numbers to the heap.
# Intuition:
#   This is similar to Dijkstra sequence generation or K-way merge.
# Time Complexity: O(n log n)
# Space Complexity: O(n)
import heapq

class SolutionHeap:
    def nthUglyNumber(self, n: int) -> int:
        heap = [1]
        seen = set(heap)
        primes = [2, 3, 5]
        for _ in range(n):
            curr = heapq.heappop(heap)
            for p in primes:
                nxt = curr * p
                if nxt not in seen:
                    heapq.heappush(heap, nxt)
                    seen.add(nxt)
        return curr

# ---------------------------
# OPTIMIZED (DP, 3 pointers)
# ---------------------------
# Approach:
#   Use dynamic programming and three pointers for multiples of 2, 3, 5 respectively.
#   At every step, choose the lowest number generated by multiplying a previous ugly number
#   by 2, 3, or 5, and increment the responsible pointer.
# Intuition:
#   The ugly number sequence is a merge of 2x, 3x, 5x the preceding sequence values.
# Time Complexity: O(n)
# Space Complexity: O(n)
class Solution:
    def nthUglyNumber(self, n: int) -> int:
        ugly = [0]*n
        ugly[0] = 1
        i2 = i3 = i5 = 0
        for i in range(1, n):
            nxt2, nxt3, nxt5 = ugly[i2]*2, ugly[i3]*3, ugly[i5]*5
            nxt = min(nxt2, nxt3, nxt5)
            ugly[i] = nxt
            if nxt == nxt2:
                i2 += 1
            if nxt == nxt3:
                i3 += 1
            if nxt == nxt5:
                i5 += 1
        return ugly[-1]